
// Auto-generated by AutoPilot on 28-07-2023 at 22:28:57


const express = require('express');
const router = express.Router();

//Array of Zlatan Jokes
const zlatanJokes = [
    "You buy a Ferrari when you become a player. When I become a player, I bought a Ferrari, a Porsche and an Audi.",
    "I don't do diving. Diving is for swimming pools, not for football.",
    "I think I'm like wine. The older I get, the better I get.",
    "When you buy me, you are buying a Ferrari.",
    "I came like a king, left like a legend.",
    "When you buy me, you are buying a Ferrari.",
    "I don't do auditions, either you know me or you don't.",
    "I won't do a handshake with a devil.",
    "I don't believe in fear.",
    "I don't think you can compare me with anyone."
];

//Route to get a random Zlatan Joke
router.get('/zlatan', (req, res) => {
    const randomJoke = zlatanJokes[Math.floor(Math.random() * zlatanJokes.length)];
    res.send(randomJoke);
});

module.exports = router;